reports/apps/arik/urls.py
from django.conf.urls import url
from reports.apps.arik import views


urlpatterns = [
               url(r'^arik/', views.index, name='arik'),
               ]

reports/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from reports.apps.arik import urls as arik_urls


urlpatterns = [
    url(r'^', include(arik_urls), name='arik'),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

reports/apps/arik/models.py
from django.db import models


class Connections(models.Model):
    title = models.CharField(max_length=200)
    database_type = models.CharField(max_length=200, default='mysql')
    database_name = models.CharField(max_length=200, default='', help_text='Name of database which consist raw tables')
    username = models.CharField(max_length=200, default='root')
    password = models.CharField(max_length=200, default='root')
    host = models.CharField(max_length=200, default='localhost')
    port = models.CharField(max_length=200, default='3306')
    machine_name = models.CharField(max_length=300, default='', blank=False)

    class Meta:
        ordering = ("-title",)
        verbose_name = u'Connection'
        verbose_name_plural = u'Connections'

    def __str__(self):
        return self.title


class ArikOrder(models.Model):
    """
    For every connection we should create new model.
    Maybe we should do it dynamically?
    """
    index = models.IntegerField(primary_key=True, db_index=True, unique=True)
    order_id = models.IntegerField(unique=True)
    mail = models.EmailField()
    order_status = models.CharField(max_length=50, default='', blank=True)
    created = models.DateTimeField()
    changed = models.DateTimeField()
    origin = models.CharField(max_length=50, default='', blank=True)
    destination = models.CharField(max_length=50, default='', blank=True)
    flight_type = models.CharField(max_length=50, default='', blank=True)
    pnr = models.CharField(max_length=50, default='')
    tickets = models.CharField(max_length=250, default='')
    passengers = models.IntegerField(blank=True, default=0)
    field_contact_phone_number_value = models.CharField(max_length=50, default='')
    payment_method = models.CharField(max_length=50, default='')
    remote_id = models.CharField(max_length=50, default='')
    message = models.CharField(max_length=150, default='')
    amount = models.IntegerField(blank=True, default=0)
    currency_code = models.CharField(max_length=50, default='')
    transaction_status = models.CharField(max_length=50, default='')
    transaction_remote_status = models.CharField(max_length=150, default='')
    # connection = models.ForeignKey(Connections, default='1')

    class Meta:
        ordering = [
            "-order_id"]
        verbose_name = u'Arik Order'
        verbose_name_plural = u'Arik Orders'

        managed = False
        db_table = 'arikair'  # or will try load it from connection

    def __str__(self):
        title = 'Order ID: ' + str(self.order_id)
        return title

reports/apps/arik/forms.py
from django import forms
from .models import Connections, ArikOrder
from django.db.models import Count


class ConnectionsForm(forms.ModelForm):
    class Meta:
        model = Connections
        fields = "__all__"
        widgets = {
            'password': forms.PasswordInput(render_value=True),
        }


class ArikTopNRoutesForm(forms.ModelForm):
    origin_query = ArikOrder.objects.order_by('origin').values_list('origin', flat=True).exclude(
        origin='').distinct()
    origin_choices = [('', 'None')] + [(id, id) for id in origin_query]

    destination_query = ArikOrder.objects.order_by('destination').values_list('destination', flat=True).exclude(
        destination='').distinct()
    destination_choices = [('', 'None')] + [(id, id) for id in destination_query]

    flight_type_query = ArikOrder.objects.order_by('flight_type').values_list('flight_type', flat=True).exclude(
        flight_type='').distinct()
    flight_type_choices = [('', 'None')] + [(id, id) for id in flight_type_query]

    order_status_query = ArikOrder.objects.order_by('order_status').values_list('order_status', flat=True).exclude(
        order_status='').distinct()
    order_status_choices = [('', 'None')] + [(id, id) for id in order_status_query]

    top_n = forms.IntegerField(initial=10, label='Top N', required=True)
    date_from = forms.DateField(widget=forms.DateInput(), required=False)
    date_to = forms.DateField(widget=forms.DateInput(), required=False)
    origin = forms.ChoiceField(origin_choices, required=False)
    destination = forms.ChoiceField(destination_choices, required=False)
    flight_type = forms.ChoiceField(flight_type_choices, required=False)
    order_status = forms.ChoiceField(order_status_choices, required=False)

    class Meta:
        model = ArikOrder
        fields = ()


class ArikPicksForm(forms.ModelForm):
    date_from = forms.DateField(widget=forms.DateInput())
    date_to = forms.DateField(widget=forms.DateInput())

    class Meta:
        model = ArikOrder
        fields = ()

reports/apps/arik/views.py
from django.shortcuts import render
from .models import ArikOrder
from .forms import ArikTopNRoutesForm, ArikPicksForm
from chartit import DataPool, Chart, PivotDataPool, PivotChart
from django.views.decorators.cache import cache_page
import pandas as pd
from django.db.models import Q
from .tables import TopTable
from django_tables2 import RequestConfig


def index(request):
    context_dict = {}
    form = ArikTopNRoutesForm()
    context_dict['form'] = form
    source = ArikOrder.objects.filter(order_status='completed')[:10]
    if request.method == 'POST':
        form = ArikTopNRoutesForm(request.POST)
        if form.is_valid():
            form_values = {'changed__gte': form.cleaned_data['date_from'], 'changed__lte': form.cleaned_data['date_to'],
                           'order_status': form.cleaned_data['order_status'], 'origin': form.cleaned_data['origin'],
                           'destination': form.cleaned_data['destination'],
                           'flight_type': form.cleaned_data['flight_type']}
            arguments = {}
            for k, v in form_values.items():
                if v:
                    arguments[k] = v
            source = ArikOrder.objects.filter(**arguments)[:form.cleaned_data['top_n']]

            orders = \
                DataPool(
                    series=
                    [{'options': {
                        'source': source},
                        'terms': [
                            "origin", "destination"]}])
            # Step 2: Create the Chart object
            cht = Chart(
                datasource=orders,
                series_options=
                [{'options': {
                    'type': 'column',
                    'stacking': False},
                    'terms': {
                        'origin': [
                            "origin"]
                    }}],
                chart_options=
                {'title': {
                    'text': 'Arik Orders data'},
                    'xAxis': {
                        'title': {
                            'text': 'Origin'}}})
            context_dict['cht'] = cht

            return render(request, 'arik.html', context_dict)

    orders = \
        DataPool(
            series=
            [{'options': {
                'source': source},
                'terms': [
                    "order_status", "origin", "destination", "flight_type",
                    "passengers", "payment_method", "currency_code", "transaction_status"]}])
    # Step 2: Create the Chart object
    cht = Chart(
        datasource=orders,
        series_options=
        [{'options': {
            'type': 'column',
            'stacking': False},
            'terms': {
                'origin': [
                    "order_status", "origin", "destination", "flight_type",
                    "passengers", "payment_method", "currency_code", "transaction_status"]
            }}],
        chart_options=
        {'title': {
            'text': 'Arik Orders data'},
            'xAxis': {
                'title': {
                    'text': 'Changed time'}}})

    # Step 3: Send the chart object to the template.
    context_dict['cht'] = cht

    return render(request, 'arik.html', context_dict)


"""
def top_n_orders(request):

    orders = ArikOrder.objects.filter(changed__gte='2016-06-23', changed__lte='2016-06-24', transaction_status='failure'
                                      ).exclude(order_status='completed').distinct()
    unique = orders.distinct()
    c = unique.count()

    form = ArikTopNRoutesForm()
    context_dict = {}
    orders = ArikOrder.objects.filter(order_status='completed')[:100]
    table = TopTable(orders)
    RequestConfig(request, paginate={'per_page': 25}).configure(table)
    context_dict['form'] = form
    #context_dict['table'] = table

    return render(request, 'arik.html', context_dict)
"""

templates/arik.html
{% extends 'starter.html' %}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
{% load staticfiles %}
{% load chartit %}
{% block content %}
     <form method="POST" class="post-form">{% csrf_token %}
        {{ form }}
        <button type="submit" class="save btn btn-default">Go</button>
    </form>
    <script>
        $(document).ready(function () {
            $('#id_date_from').datepicker({
                defaultDate: "-1w",
                changeMonth: true,
                changeYear: true,
                showAnim: 'slideDown'
            });
            $('#id_date_to').datepicker({
                defaultDate: "-1w",
                changeMonth: true,
                changeYear: true,
                showAnim: 'slideDown'
            });
        });
    </script>
    {{ cht|load_charts:"container" }}
    <div id='container'> Chart will be rendered here</div>
{{ test }}
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="ru">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="This one page example has a fixed navbar and full page height sections. Each section is vertically centered on larger screens, and then stack responsively on smaller screens. Scrollspy is used to activate the current menu item. This layout also has a contact form example. Uses animate.css, FontAwesome, Google Fonts (Lato and Bitter) and Bootstrap." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{%  static 'css/styles.css' %}">

</head>
<body>
{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
{% endblock %}

templates/pick.html
{% extends 'starter.html' %}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
{% load staticfiles %}
{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ pick_form }}
        <button type="submit" class="save btn btn-default">Go</button>
    </form>
    {{ ff | safe }}
{% endblock %}

templates/right_now.html
<div id="data_now">{{ data_now }}</div>

templates/starter.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{% static 'adminlte/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <script src="{% static 'adminlte/plugins/jQuery/jQuery-2.2.0.min.js' %}"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

    <script src="http://code.highcharts.com/highcharts.js"></script>

    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/skin-blue.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <!-- Main Header -->
    <header class="main-header">
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- search form (Optional) -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
                </div>
            </form>
            <!-- /.search form -->

            <!-- Sidebar Menu -->
            <ul class="sidebar-menu">
                <li class="header">HEADER</li>
                <!-- Optionally, you can add icons to the links -->
                <li class="active"><a href="#"><i class="fa fa-link"></i> <span>Link</span></a></li>
                <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
                <li class="treeview">
                    <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span> <i
                            class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li><a href="#">Link in level 2</a></li>
                        <li><a href="#">Link in level 2</a></li>
                    </ul>
                </li>
            </ul>
            <!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {% block header %}
                {% endblock %}
                <small>
                    {% block header_description %}
                    {% endblock %}
                </small>
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">

            {% block content %}
            {% endblock %}

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
        {% block footer %}

            <!-- To the right -->
            <div class="pull-right hidden-xs">
                {% block footer_right %}{% endblock %}
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
        {% endblock %}
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
            <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
            <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <!-- Home tab content -->
            <div class="tab-pane active" id="control-sidebar-home-tab">
                <h3 class="control-sidebar-heading">Recent Activity</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="javascript::;">
                            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                            <div class="menu-info">
                                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                                <p>Will be 23 on April 24th</p>
                            </div>
                        </a>
                    </li>
                </ul>
                <!-- /.control-sidebar-menu -->

                <h3 class="control-sidebar-heading">Tasks Progress</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="javascript::;">
                            <h4 class="control-sidebar-subheading">
                                Custom Template Design
                                <span class="label label-danger pull-right">70%</span>
                            </h4>

                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                            </div>
                        </a>
                    </li>
                </ul>
                <!-- /.control-sidebar-menu -->

            </div>
            <!-- /.tab-pane -->
            <!-- Stats tab content -->
            <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
            <!-- /.tab-pane -->
            <!-- Settings tab content -->
            <div class="tab-pane" id="control-sidebar-settings-tab">
                <form method="post">
                    <h3 class="control-sidebar-heading">General Settings</h3>

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            Report panel usage
                            <input type="checkbox" class="pull-right" checked>
                        </label>

                        <p>
                            Some information about this general settings option
                        </p>
                    </div>
                    <!-- /.form-group -->
                </form>
            </div>
            <!-- /.tab-pane -->
        </div>
    </aside>
    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.2.0 -->

<!-- Bootstrap 3.3.6 -->
<script src="{% static 'adminlte/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/dist/js/app.min.js' %}"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. Slimscroll is required when using the
     fixed layout. -->
</body>
</html>

templates/top_n_orders.html
{% load chartit %}
{% block content %}
    <script>
        $(document).ready(function () {
            $('#id_date_from').datepicker({
                defaultDate: "-1w",
                changeMonth: true,
                changeYear: true,
                showAnim: 'slideDown'
            });
            $('#id_date_to').datepicker({
                defaultDate: "-1w",
                changeMonth: true,
                changeYear: true,
                showAnim: 'slideDown'
            });
        });
    </script>
    {{ cht|load_charts:"container" }}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form }}
        <button type="submit" class="save btn btn-default">Go</button>
    </form>
    <div id='container'> Chart will be rendered here</div>
{% endblock %}